#!/bin/bash
# =============================================================================
# LinkedIn Bot — One-Click VPS Deployment
# Tested on: Ubuntu 22.04 / 24.04 (Hetzner, DigitalOcean, Vultr, AWS Lightsail)
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/zackwhy1704/linkedin-automation-bot/master/deploy-vps.sh | bash
#   OR
#   bash deploy-vps.sh
# =============================================================================
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""
echo "=============================================="
echo "  LinkedIn Bot — VPS Deployment"
echo "=============================================="
echo ""

# ─── Gather config ───────────────────────────────────────────────────
read -p "Enter your domain name (e.g., bot.yourdomain.com): " DOMAIN
if [ -z "$DOMAIN" ]; then
    echo -e "${RED}ERROR: Domain is required for HTTPS.${NC}"
    echo "Point an A record to this server's IP first, then re-run."
    exit 1
fi

read -p "GitHub repo URL [https://github.com/zackwhy1704/linkedin-automation-bot.git]: " REPO_URL
REPO_URL=${REPO_URL:-https://github.com/zackwhy1704/linkedin-automation-bot.git}

APP_DIR="/opt/linkedin-bot"

# ─── 1. Install Docker ──────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[1/6] Installing Docker...${NC}"
if command -v docker &>/dev/null; then
    echo -e "${GREEN}  Docker already installed: $(docker --version)${NC}"
else
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo -e "${GREEN}  Docker installed: $(docker --version)${NC}"
fi

# Install docker compose plugin if not present
if ! docker compose version &>/dev/null; then
    apt-get update -y && apt-get install -y docker-compose-plugin
fi
echo -e "${GREEN}  Docker Compose: $(docker compose version)${NC}"

# ─── 2. Firewall ────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[2/6] Configuring firewall...${NC}"
if command -v ufw &>/dev/null; then
    ufw allow OpenSSH
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw --force enable
    echo -e "${GREEN}  Firewall: SSH, HTTP, HTTPS allowed${NC}"
else
    echo "  ufw not found, skipping firewall setup"
fi

# ─── 3. Clone repository ────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[3/6] Cloning repository...${NC}"
if [ -d "$APP_DIR" ]; then
    cd "$APP_DIR"
    git pull
    echo -e "${GREEN}  Updated existing repo${NC}"
else
    git clone "$REPO_URL" "$APP_DIR"
    echo -e "${GREEN}  Cloned to $APP_DIR${NC}"
fi
cd "$APP_DIR"

# ─── 4. Create .env.production ──────────────────────────────────────
echo ""
echo -e "${YELLOW}[4/6] Configuring environment...${NC}"
if [ -f "$APP_DIR/.env.production" ] && grep -q "YOUR_TELEGRAM_BOT_TOKEN" "$APP_DIR/.env.production"; then
    echo "  .env.production has placeholder values. Let's fill them in."
    NEEDS_CONFIG=true
elif [ ! -f "$APP_DIR/.env.production" ]; then
    NEEDS_CONFIG=true
else
    echo -e "${GREEN}  .env.production already configured${NC}"
    NEEDS_CONFIG=false
fi

if [ "$NEEDS_CONFIG" = true ]; then
    echo ""
    echo "  Fill in your credentials (press Enter to keep default):"
    echo ""

    read -p "  Telegram Bot Token: " TELEGRAM_TOKEN
    read -p "  Stripe Secret Key (sk_live_...): " STRIPE_KEY
    read -p "  Stripe Price ID (price_...): " STRIPE_PRICE
    read -p "  Stripe Webhook Secret (whsec_...): " STRIPE_WEBHOOK
    read -p "  Anthropic API Key (sk-ant-...): " ANTHROPIC_KEY
    read -p "  Encryption Key (or press Enter to generate): " ENC_KEY

    # Generate encryption key if not provided
    if [ -z "$ENC_KEY" ]; then
        ENC_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || openssl rand -base64 32)
    fi

    # Generate strong DB password
    DB_PASS=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)

    cat > "$APP_DIR/.env.production" <<ENVEOF
# Auto-generated by deploy-vps.sh on $(date)
LINKEDIN_EMAIL=
LINKEDIN_PASSWORD=
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
HEADLESS=True
BROWSER=chrome
MIN_DELAY=2
MAX_DELAY=5
SCROLL_DELAY=1
MAX_LIKES_PER_SESSION=5
MAX_COMMENTS_PER_SESSION=5
MAX_MESSAGES_PER_SESSION=5
RANDOMIZE_ACTIONS=True
USE_HUMAN_DELAYS=True
TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
STRIPE_SECRET_KEY=${STRIPE_KEY}
STRIPE_PRICE_ID=${STRIPE_PRICE}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK}
ENCRYPTION_KEY=${ENC_KEY}
DATABASE_HOST=db
DATABASE_PORT=5432
DATABASE_NAME=linkedin_bot
DATABASE_USER=linkedin_bot
DATABASE_PASSWORD=${DB_PASS}
PAYMENT_SERVER_URL=https://${DOMAIN}
WEBAPP_URL=https://${DOMAIN}
REDIS_URL=redis://redis:6379/0
ENVEOF

    chmod 600 "$APP_DIR/.env.production"
    echo -e "${GREEN}  .env.production created${NC}"
fi

# ─── 5. Set domain in Caddyfile ─────────────────────────────────────
echo ""
echo -e "${YELLOW}[5/6] Configuring HTTPS for ${DOMAIN}...${NC}"

# Export DOMAIN for docker-compose
echo "DOMAIN=${DOMAIN}" > "$APP_DIR/.env.docker"
echo -e "${GREEN}  Caddy will auto-provision Let's Encrypt cert for ${DOMAIN}${NC}"

# ─── 6. Build and start ─────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[6/6] Building and starting services...${NC}"
echo "  This will take 3-5 minutes on first run (downloading Chrome, Python packages)..."
echo ""

cd "$APP_DIR"

# Pass DOMAIN env var to Caddy
export DOMAIN="$DOMAIN"

# Build and start all services
docker compose --env-file .env.docker build
docker compose --env-file .env.docker up -d

# Wait for services to be healthy
echo ""
echo "  Waiting for services to start..."
sleep 15

# ─── Status check ───────────────────────────────────────────────────
echo ""
echo "=============================================="
echo -e "${GREEN}  Deployment Complete!${NC}"
echo "=============================================="
echo ""

docker compose ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"

echo ""
echo "=============================================="
echo "  Your Bot URLs"
echo "=============================================="
echo ""
echo -e "  Bot:          https://t.me/$(echo $TELEGRAM_TOKEN | cut -d: -f1 | xargs -I{} echo 'your_bot')"
echo -e "  Payment:      ${GREEN}https://${DOMAIN}/payment/success${NC}"
echo -e "  Webhook:      ${GREEN}https://${DOMAIN}/webhook/stripe${NC}"
echo -e "  Health:       ${GREEN}https://${DOMAIN}/health${NC}"
echo ""
echo "=============================================="
echo "  Next Steps"
echo "=============================================="
echo ""
echo "  1. Update Stripe webhook URL to:"
echo -e "     ${GREEN}https://${DOMAIN}/webhook/stripe${NC}"
echo ""
echo "  2. Scale workers for more concurrent users:"
echo "     cd $APP_DIR && docker compose up -d --scale worker=5"
echo ""
echo "  3. View logs:"
echo "     docker compose logs -f bot"
echo "     docker compose logs -f worker"
echo "     docker compose logs -f payment"
echo ""
echo "  4. Redeploy after code changes:"
echo "     cd $APP_DIR && git pull && docker compose build && docker compose up -d"
echo ""
echo "  5. Export local database and import:"
echo "     On Windows: run deployment/migrate_db_export.bat"
echo "     Then: scp linkedin_bot_export.sql root@SERVER_IP:$APP_DIR/"
echo "     Then: docker compose exec db psql -U linkedin_bot -d linkedin_bot -f /app/linkedin_bot_export.sql"
echo ""
